###########################################################################
# BUILD-RUNBOOK.PS1
# ASSEMBLES THE FINOPS SCAN RUNBOOK FROM MODULE FILES
###########################################################################
# Purpose: Concatenates all scan modules + the runbook script into a
#          single self-contained .ps1 file for Azure Automation.
# Usage:   .\Build-Runbook.ps1
# Output:  runbook\Run-FinOpsScan-Assembled.ps1
###########################################################################

$ErrorActionPreference = 'Stop'

$root = Split-Path $PSScriptRoot -Parent
$modulePath = Join-Path $root 'function-app\modules'
$runbookPath = Join-Path $root 'runbook\Run-FinOpsScan.ps1'
$outputPath = Join-Path $root 'runbook\Run-FinOpsScan-Assembled.ps1'

$modules = @(
    'Invoke-AzRestMethodWithRetry.ps1',
    'Search-AzGraphSafe.ps1',
    'Read-FinOpsHubData.ps1',
    'Get-TenantHierarchy.ps1',
    'Get-ContractInfo.ps1',
    'Get-CostData.ps1',
    'Get-ResourceCosts.ps1',
    'Get-TagInventory.ps1',
    'Get-CostByTag.ps1',
    'Get-AhbVmSavingsRatio.ps1',
    'Get-AHBOpportunities.ps1',
    'Get-ReservationAdvice.ps1',
    'Get-OptimizationAdvice.ps1',
    'Get-TagRecommendations.ps1',
    'Get-CostTrend.ps1',
    'Get-BillingStructure.ps1',
    'Get-CommitmentUtilization.ps1',
    'Get-OrphanedResources.ps1',
    'Get-BudgetStatus.ps1',
    'Get-AnomalyAlerts.ps1',
    'Get-SavingsRealized.ps1',
    'Get-PolicyInventory.ps1',
    'Get-PolicyRecommendations.ps1',
    'Get-StorageTierAdvice.ps1',
    'Get-IdleVMs.ps1',
    'New-FinOpsHtmlReport.ps1'
)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# ═══════════════════════════════════════════════════════════════════════")
[void]$sb.AppendLine("# ASSEMBLED FINOPS SCAN RUNBOOK")
[void]$sb.AppendLine("# Auto-generated by Build-Runbook.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
[void]$sb.AppendLine("# Do not edit this file directly — edit the source modules instead.")
[void]$sb.AppendLine("# ═══════════════════════════════════════════════════════════════════════")
[void]$sb.AppendLine("")

$loaded = 0
foreach ($mod in $modules) {
    $modFile = Join-Path $modulePath $mod
    if (-not (Test-Path $modFile)) {
        Write-Warning "Module not found: $modFile"
        continue
    }
    $content = Get-Content $modFile -Raw
    # Strip decorative ###...### header lines - Azure Automation chokes on them
    $content = ($content -split "`r?`n" | Where-Object { $_ -notmatch '^\s*#{10,}\s*$' }) -join "`r`n"
    [void]$sb.AppendLine("# ── Module: $mod ──")
    [void]$sb.AppendLine($content.TrimEnd())
    [void]$sb.AppendLine("")
    $loaded++
}

Write-Host "Embedded $loaded modules"

# Append the main runbook
$runbook = Get-Content $runbookPath -Raw
$runbook = ($runbook -split "`r?`n" | Where-Object { $_ -notmatch '^\s*#{10,}\s*$' }) -join "`r`n"
[void]$sb.AppendLine("# ── Main Runbook ──")
[void]$sb.AppendLine($runbook.TrimEnd())

$assembled = $sb.ToString()
Set-Content -Path $outputPath -Value $assembled -Encoding UTF8 -NoNewline
Write-Host "Written to: $outputPath"
Write-Host "Total size: $([math]::Round($assembled.Length / 1024, 1)) KB"
